# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 433990e564fbd5c50df8d0efdc1a9ed95f78057d009021d06fedfaee144fb685c8acf782c910cc7a3a7e7e70bcd94dba48a7804366189feab0b09669ce20a032

test:
  secret_key_base: 484059033a0a51050ab9075ac342900ef04dffd3ac8c91d8e5ab2435c1561de3dce697a1f8ce191b2e9bbe44fa1c45c0746bb4edef9a2d8e7453d01bd0cf3f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
